version = 0.1

[default.global.parameters]
stack_name = "smart-device-api-stack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
s3_bucket = "sam-artifacts-iot-2025"

confirm_changeset = true
resolve_s3 = true
fail_on_empty_changeset = false
s3_prefix = "smartdevice-sam-artifacts-gsinbandera"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
region = "us-east-1"
image_repositories = []
disable_rollback = true
stack_name = "smartdevice-sam-artifacts-gsinbandera"

[default.package.parameters]
resolve_s3 = false
s3_bucket = "sam-artifacts-iot-2025"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
