AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: smart-device-api

Globals:
  Function:
    Timeout: 5
    Tracing: Active

Resources:

  ## --- Cognito User Pool ---
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: SmartDeviceUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: true
          RequireSymbols: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: smart-device-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - http://localhost:3000/callback
        - https://app.domoticore.co/callback
      LogoutURLs:
        - http://localhost:3000/logout
        - https://app.domoticore.co/logout
      SupportedIdentityProviders:
        - COGNITO

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: smart-device-demo-domain
      UserPoolId: !Ref CognitoUserPool

  ## --- API Gateway ---
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SmartDeviceApi
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Authorization,Content-Type'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
            Identity:
              Header: Authorization

  ## --- Lambda Functions ---
  GetDevicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-devices/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Events:
        GetDevices:
          Type: Api
          Properties:
            Path: /devices
            Method: get
            RestApiId: !Ref MyApi
            Auth:
              Authorizer: CognitoAuthorizer
        DevicesOptions:
          Type: Api
          Properties:
            Path: /devices
            Method: options
            RestApiId: !Ref MyApi
            Auth:
              Authorizer: NONE
      Environment:
        Variables:
          DEVICES_TABLE: Devices
          DEVICE_ALIASES_TABLE: deviceAliases
          USERS_TABLE: Users
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Devices
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Devices/index/user_id-index
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/deviceAliases
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Users

  ## --- Nested Stacks para tablas DynamoDB ---
  DevicesTableStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Retain
    Properties:
      Location: ./sam-templates/tables/devices.yml

  UsersTableStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Retain
    Properties:
      Location: ./sam-templates/tables/users.yml

  DeviceAliasesTableStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Retain
    Properties:
      Location: ./sam-templates/tables/device-aliases.yml

  RaspberryPisTableStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Retain
    Properties:
      Location: ./sam-templates/tables/raspberry-pis.yml

  SharedAccessTableStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Retain
    Properties:
      Location: ./sam-templates/tables/shared-access.yml

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  GetDevicesFunctionArn:
    Description: "ARN of GetDevices Lambda"
    Value: !GetAtt GetDevicesFunction.Arn

  CognitoUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool

  CognitoUserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient

  CognitoUserPoolDomain:
    Description: "Cognito Domain"
    Value: !Ref CognitoUserPoolDomain
