AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB DeviceAliases table for SmartDeviceApi

Resources:

  DeviceAliasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: deviceAliases
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
        - AttributeName: gpio
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
        - AttributeName: gpio
          KeyType: RANGE
      # Items also include:
      # - aliases (lista de strings que representan los alias de cada GPIO)
