AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB RaspberryPIs table for SmartDeviceApi

Resources:

  RaspberryPIsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RaspberryPIs
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: raspi_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: raspi_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      # Items will include:
      # - user_id       (dueño de esta Raspberry Pi)
      # - registered_at (ISO8601 timestamp)
      # - is_active     (boolean)
      # - location      (string descriptiva)
      # - device_ids    (lista de device_id conectados, opcional)
