AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB SharedAccess table for SmartDeviceApi

Resources:

  SharedAccessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SharedAccess
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: raspi_id
          AttributeType: S
        - AttributeName: shared_with
          AttributeType: S
      KeySchema:
        - AttributeName: raspi_id
          KeyType: HASH
        - AttributeName: shared_with
          KeyType: RANGE
      # Items will include:
      # - role       (string, e.g. "viewer" or "controller")
      # - granted_at (ISO8601 timestamp, string)
