AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Users table for SmartDeviceApi

Resources:

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      # Items will include additional attributes:
      # - created_at (ISO8601 timestamp, string)
      # - email      (string)
      # - is_active  (boolean)
      # - name       (string)
