Resources:

  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Devices
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: raspi_id
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: raspi_id-index
          KeySchema:
            - AttributeName: raspi_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      # Items will also include these non-key attributes:
      # - raspi_id        (qué Raspberry Pi lo hospeda)
      # - type            (p.ej. "board", "sensor", etc.)
      # - analog_inputs   (número de entradas analógicas)
      # - analog_outputs  (número de salidas analógicas)
      # - digital_inputs  (número de entradas digitales)
      # - digital_outputs (número de salidas digitales)
      # - user_id         (dueño del dispositivo)
